version: '3'
services:

  dockerflaskclient:
      build:
        context: .
        dockerfile: Dockerfile
      container_name: flask-client
      ports: 
        - 5001:5001
      entrypoint:
        - flask
        - run
        - --host=0.0.0.0
        - --port=5001
      environment: 
        - FLASK_DEBUG=1
        - FLASK_APP=./app.py
      volumes:
        - './:/app'
        - './dossier_images:/image_dir'
        