name: Python Package

on:  # Déclencheurs d'événements
  push:
    branches: [ main ]  # Exécutez ce workflow sur chaque push à la branche main
  pull_request:
    branches: [ main ]  # Exécutez ce workflow sur chaque pull request vers la branche main

jobs:
  build:
    runs-on: ubuntu-latest  # Utilisez la dernière version d'Ubuntu

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Récupérer le code du dépôt

      - name: Set up Python
        uses: actions/setup-python@v2  # Configurer Python
        with:
          python-version: '3.8'  # Spécifiez la version de Python à utiliser

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Installer les dépendances

      - name: Run tests
        run: |
          pytest  tests/test_def.py